### PR TITLE
No longer wraps 'interval' with parentheses 

### LINKED ISSUE #305: InMemoryAggregate.abort() causes org.h2.jdbc.JdbcSQLException: Method is only allowed for a query.
org.h2.jdbc.JdbcSQLException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
SHUTDOWN [90002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Prepared.query(Prepared.java:219)
	at org.h2.command.CommandContainer.query(CommandContainer.java:114)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at org.verdictdb.connection.InMemoryAggregate.abort(InMemoryAggregate.java:181)
	at org.verdictdb.core.querying.ola.SelectAsyncAggExecutionNode.abort(SelectAsyncAggExecutionNode.java:191)
	at org.verdictdb.core.execplan.ExecutableNodeRunner.abort(ExecutableNodeRunner.java:138)
	at org.verdictdb.core.execplan.ExecutablePlanRunner.abort(ExecutablePlanRunner.java:131)
	at org.verdictdb.coordinator.SelectQueryCoordinator.abort(SelectQueryCoordinator.java:174)
	at org.verdictdb.coordinator.ExecutionContext.abort(ExecutionContext.java:420)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:162)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:123)
	at org.verdictdb.jdbc41.VerdictStatement.executeQuery(VerdictStatement.java:135)
	at org.verdictdb.core.scramblingquerying.TpchScrambleQueryForAllDatabasesTest.testTpch(TpchScrambleQueryForAllDatabasesTest.java:329)

I think changing it from executeQuery to execute should fix it.

### PR DESCRIPTION
**Pull request by dongyoungy**
- Add extra unit tests to test tpc-h + scramble
- Also fix #305

### CODE REVIEW

**Comment by pyongjoo** [comment]
Can you check the build failure in the master? https://circleci.com/gh/mozafari/verdictdb/2700

**Comment by dongyoungy** [comment]
It has been caused by redshift unit tests, which happen to share the same schema for ScrambleMeta:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "hashColumn" (class org.verdictdb.core.scrambling.ScrambleMeta), not marked as ignorable (10 known properties: "aggregationBlockColumn", "aggregationBlockCount", "originalTableName", "tableName", "schemaName", "originalSchemaName", "numberOfTiers", "tierColumn", "cumulativeDistributions", "method"])
 at [Source: {"schemaName":"verdictdb_tpch_query_test_g0kijsbq","tableName":"orders_scramble","originalSchemaName":"verdictdb_tpch_query_test_g0kijsbq","originalTableName":"orders","aggregationBlockColumn":"verdictdbblock","aggregationBlockCount":1,"tierColumn":"verdictdbtier","numberOfTiers":1,"method":"uniform","hashColumn":null,"cumulativeDistributions":{"0":[1.0]}}; line: 1, column: 320] (through reference chain: org.verdictdb.core.scrambling.ScrambleMeta["hashColumn"])
```

I guess added `hashColumn` field in ScrambleMeta in the ongoing work on supporting count distinct affected the test in master branch. 

I think It should get cleared once you push your latest work into master, yet I will try to have those failed tests to use different randomized schema for meta.

**Comment by pyongjoo** [comment]
I see. Then, I guess there’s no need to temporarily fix it. I’ll just merge mine once I fix my errors.

**Comment by dongyoungy** [comment]
It looks like some Presto unit tests in `pyverdict` job also have same problem: [https://circleci.com/gh/mozafari/verdictdb/2741](https://circleci.com/gh/mozafari/verdictdb/2741)

**Comment by pyongjoo** [comment]
I feel like there was a temporary network error in CircleCI or so. Let me double-check.

**Comment by pyongjoo** [comment]
All tests are passing now for the code in the `yongjoo-count-distinct` branch.

**Pull request merged**
