### PR TITLE
Add support for spatial functions in Presto

### LINKED ISSUE #290: Add support for Presto's spatial joins/functions
These are TODO items I could think of:
1. Add keywords in ANTLR parser/lexer
2. Add a parsing logic for SQL string to SQL objects
2. Add writing logic for SQL objects to SQL string

### LINKED ISSUE #292: Preventing null catalog name for Presto
The following error occurred when an empty catalog name was passed for a Presto connection. I think we can simply throw an error if the catalog name is not specified (similar to Redshift).

```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling z:org.verdictdb.VerdictContext.fromConnectionString.
E                   : org.verdictdb.exception.VerdictDBDbmsException: Issued the following query: create schema if not exists verdictdbtemp
E                   Query failed (#20181108_210739_00526_3zuzf): line 1:1: Catalog must be specified when session catalog is not set
E                   	at org.verdictdb.connection.JdbcConnection.executeSingle(JdbcConnection.java:170)
E                   	at org.verdictdb.connection.JdbcConnection.execute(JdbcConnection.java:130)
E                   	at org.verdictdb.connection.ConcurrentJdbcConnection.execute(ConcurrentJdbcConnection.java:134)
E                   	at org.verdictdb.connection.CachedDbmsConnection.execute(CachedDbmsConnection.java:49)
E                   	at org.verdictdb.connection.DbmsConnection.execute(DbmsConnection.java:41)
E                   	at org.verdictdb.VerdictContext.initialize(VerdictContext.java:98)
E                   	at org.verdictdb.VerdictContext.<init>(VerdictContext.java:79)
E                   	at org.verdictdb.VerdictContext.fromConnectionString(VerdictContext.java:152)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by dongyoungy**
- Add support for spatial functions in Presto (resolve #290) (Used this [presto documentation](https://prestodb.io/docs/current/functions/geospatial.html) as a reference) - These may or may not work with other DBs for now
- Add a few simple unit tests for basic function like ST_POINT, ST_CONTAINS (resolve #290)
- Throw an exception when a session catalog is not set for Presto connections (fix #292)
- Temp fix for QueryResultAccuracyEstimationFromDifference as a recent change does not seem to work correctly for "SELECT *" (PR #276)

@pyongjoo I did not add the CLI myself. I will work on spatial query testing once it is ready.
@Beastjoe If you have time, it would be great if you can take a look at the issue with QueryResultAccuracyEstimationFromDifference (#276) that I have found and see what you can do other than my temporary fix.

### CODE REVIEW

**Comment by dongyoungy** [comment]
FYI, QueryResultAccuracyEstimationFromDifference caused the following IndexOutOfBoundsException before the temporary fix:

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.verdictdb.coordinator.QueryResultAccuracyEstimatorFromDifference.checkConverge(QueryResultAccuracyEstimatorFromDifference.java:64)
	at org.verdictdb.coordinator.QueryResultAccuracyEstimatorFromDifference.isLastResultAccurate(QueryResultAccuracyEstimatorFromDifference.java:45)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:152)
	at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:123)
	at org.verdictdb.jdbc41.VerdictStatement.executeQuery(VerdictStatement.java:135)
	at org.verdictdb.jdbc41.PrestoSpatialQueryTest.runSimpleSelectSTContainsTest(PrestoSpatialQueryTest.java:171)
```

**Comment by voycey** [comment]
The primary functions for spatial joins are the ST_WITHIN, ST_CONTAINS and ST_INTERSECTS, I think the majority of use cases would use these.
These functions will work in most SQL / OGC supported databases as well (PostGIS for example would become wildly more useful with verdict)

**Comment by pyongjoo** [comment]
@dongyoungy I am still working on CLI (https://github.com/mozafari/verdictdb/issues/249). I will try to finish the Presto part at least by tomorrow.

**Comment by Beastjoe** [comment]
@dongyoungy Can I know the environment variables to run the test locally? Thanks!

```
    PRESTO_HOST = System.getenv("VERDICTDB_TEST_PRESTO_HOST");
    PRESTO_CATALOG = System.getenv("VERDICTDB_TEST_PRESTO_CATALOG");
    PRESTO_USER = System.getenv("VERDICTDB_TEST_PRESTO_USER");
    PRESTO_PASSWORD = System.getenv("VERDICTDB_TEST_PRESTO_PASSWORD");
```

**Comment by pyongjoo** [comment]
@Beastjoe https://github.com/verdictdb/verdictdb-dev/wiki/Development-env-setup-list

**Comment by pyongjoo** [comment]
@dongyoungy I just published the first pyverdict version. Please see the example below. I will make the interface more friendly and add formal documentation later.

## Install
Type the following in bash. I used Python3.6 from [Anaconda](https://www.anaconda.com/download/#macos)

```bash
pip install pyverdict
```

## Using pyverdict

```python
import os
import pyverdict

print(pyverdict.__version__)    # this should be '0.1.2.2'

hostport = os.environ['VERDICTDB_TEST_PRESTO_HOST']
host, port = hostport.split(':')
port = int(port)
catalog = os.environ['VERDICTDB_TEST_PRESTO_CATALOG']
user = os.environ['VERDICTDB_TEST_PRESTO_USER']

connection_string = 'jdbc:presto://{:s}:{:d}/{:s}?user={:s}'.format(host, port, catalog, user)
verdict = pyverdict.VerdictContext(connection_string)
result = verdict.sql('show schemas')
print(results.rows())
```

**Comment by dongyoungy** [comment]
I am trying to use it on the test cluster. One thing I have found is that pyverdict.VerdictContext() requires classpath for VerdictDB and other JDBC jars. I had to do something like following to make it work:
```python
cp = ['/home/dyoon/verdictdb/target/verdictdb-core-0.5.7-SNAPSHOT-jar-with-dependencies.jar', '/home/dyoon/verdictdb/presto-jdbc-0.213.jar']
vc = pyverdict.VerdictContext(connection_string, cp)
```

**Comment by pyongjoo** [comment]
FYI, I have updated pyverdict to include jar files by default. Also, I have changed the interface in a simpler way.

After updating with `pip install pyverdict --upgrade`, one can do
```
import pyverdict
verdict = pyverdict.presto_context(host, catalog, user, port=port)
print(verdict.sql('show schemas'))
```

I have also added related quickstart guide, which won't appear though until tpch10g tests are cleared and the pyverdict pull request is merged.

**Comment by pyongjoo** [comment]
@Beastjoe Can you check the places where the java.sql.Statement are left open for H2 database, and close them? Besides deadlocks, it could save some resources as well.

**Comment by dongyoungy** [comment]
Here are performance numbers on a simple spatial query test.

The test spatial query used is as follows (this roughly returns the number of POIs in Michigan):
```sql
SELECT count(*) FROM default.raw WHERE ST_CONTAINS(ST_POLYGON('polygon ((40 -85, 45 -85, 45 -83, 41 -83, 40 -85))'), ST_POINT(lat,lon))
```

The original query returned `199950686` and took 24 min 50 seconds (i.e., 1490 seconds)

The approximate query on the scramble with size 0.01 returned `199190000` and took 3.81 seconds.

The actual relative error was about 0.3% with 391x speed up.

**Comment by pyongjoo** [comment]
Thanks for the update.

After @Beastjoe finishes https://github.com/mozafari/verdictdb/pull/299, let's merge this pull request into master. Then, pyvedict pull request can also be merged. FYI, although including H2 DB as a regular dependency introduces the unwanted `java.sql.Driver` metadata file, I have fixed it in my branch with maven shade plugin.

I am working on supporting count-distinct with hash-based sampling.

**Comment by voycey** [comment]
This is great news guys :)

**Comment by pyongjoo** [comment]
I just merged https://github.com/mozafari/verdictdb/pull/299. I believe this pull request can also be merged after rebasing on master.

**Pull request merged**
