### PR TITLE
Disable unit tests that use private resources

### PR DESCRIPTION
**Pull request by dongyoungy**
This is an attempt to enable automatic unit tests on external pull requests via CircleCI.
This PR:
1) disable unit tests using our private resources via `@Ignore` annotation
2) comment out `git pull` on our private resources in the CircleCI configuration

Please note that:
1) Currently our Redshift test instance is down, so CircleCI tests will fail
2) There has been issue with CircleCI image that we use for our jdk7 tests: https://discuss.circleci.com/t/apt-get-update-return-404/29237/8
I have included a temporary fix to it, but we may need to use a different image for a proper fix.

### CODE REVIEW

**Comment by pyongjoo** [comment]
I think it looks good. Let me disable the private repo itself and let you know. In this way, we can fundamentally guarantee no access to the repo.

**Comment by pyongjoo** [comment]
@dongyoungy Currently, the errors are due to our stopped Redshift cluster.  Can you also simply deactivate those unit tests?

**Comment by pyongjoo** [comment]
@dongyoungy Can you fix the error and merge this to the master?  Not urgent, but I would like to base my branch on this.

**Comment by dongyoungy** [comment]
I have further disabled unit tests with redshift since all unit tests get passed, I am merging this PR.

**Pull request merged**
